name: Build and Publishs

on:
  create:
    branches:
      - release/**
  push:
    branches:
      - main
      - release/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SOLUTION: JMDict.sln

    steps:
      - uses: actions/checkout@v3

      - name: Get Build Version
        id: get_version
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/release/"* ]]; then
            echo "VERSION=$(echo ${GITHUB_REF#refs/heads/release/})" >> $GITHUB_ENV
          else
            echo "VERSION=1.0.0" >> $GITHUB_ENV
          fi

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build /p:Version=${{ env.VERSION }} $SOLUTION --configuration Release --no-restore

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push **/*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{ secrets.NUGET_API_KEY }}
        env:
          NUGET_VERSION: ${{ env.VERSION }}
