name: CIp

on:
  create:
    branches:
      - release/**
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: Release
      SOLUTION: JMDict.sln

    steps:
      - uses: actions/checkout@v3

      - name: Get Build Version
        id: get_version
        run: |
          echo "::set-output name=version::$(echo ${{ github.ref }} | sed -n -e 's/^refs\/tags\/v\{0,1\}\(.*\)$/\1/p')"
        shell: bash

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Publish
        if: startsWith(github.ref, 'refs/heads/release')
        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
        env:
          NUGET_VERSION: ${{ steps.get_version.outputs.version }}
